version: '3'
services:
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
    volumes:
      - ./tmp/db:/var/lib/mysql/
  app:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle
      - node_modules:/app/nodo_modules
      - bundle:/app/.bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle_install:
  bundle:
  node_modules:
  
